=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad6/ModuloCFGS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    
    <xs:element name="moduloCFGS">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="modulo" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="nombre" type="xs:string"/>
                                <xs:element name="contenidos" maxOccurs="1">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="UD" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                            <xs:element name="tipo" type="xs:string"/>
                                                            <xs:element name="descripcion" type="xs:string"/>
                                                    </xs:sequence>
                                                    <xs:attribute name="numero" type="xs:string"/>        
                                                </xs:complexType>            
                                            </xs:element>       
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
    </xs:element>

</xs:schema>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad6/ModuloCFGS_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<moduloCFGS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ModuloCFGS.xsd"></moduloCFGSxmlns:xsi>>
    <modulo>
        <nombre>Lenguajes de marcas y sistemas de gestión de información</nombre>
        <contenidos>
            <UD numero="1">
                <tipo>Introducción a los lenguajes de marcas</tipo>
                <descripcion>Introducción a la asignatura de lenguajes de marcas y sistemas de gestión de la información</descripcion>
            </UD>
            <UD numero="2">
                <tipo>Lenguajes para la visualización de información</tipo>
                <descripcion>Introducción y uso de HTML y CSS</descripcion>
            </UD>
            <UD numero="3">
                <tipo>Lenguajes para el almacenamiento y transmisión de información</tipo>
                <descripcion>Como usar XML, estructura y sintaxis</descripcion>
            </UD>
        </contenidos>
    </modulo>
    <modulo>
        <nombre>Bases de Datos</nombre>
        <contenidos>
            <UD numero="1">
                <tipo>Almacenamiento de la información</tipo>
                <descripcion>Introducción a los métodos de almacenamiento de la información. Historia, ficheros y tipos de almacenamiento</descripcion>
            </UD>
            <UD numero="2">
                <tipo>Bases de datos relacionales</tipo>
                <descripcion>Modelo relacional. Características y su uso</descripcion>
            </UD>
            <UD numero="3">
                <tipo>Modelo Entidad/Relación</tipo>
                <descripcion>Introducción, elementos y extensiones del modelo E/R</descripcion>
            </UD>
        </contenidos>
    </modulo>
    <modulo>
        <nombre>Entornos de desarrollo</nombre>
        <contenidos>
            <UD numero="1">
                <tipo>Desarrollo de software</tipo>
                <descripcion>Tipos de paradigmas, tipos de código, lenguajes de programación, roles del desarrollo y arquitectura del software</descripcion>
            </UD>
            <UD numero="2">
                <tipo>Instalación y uso de entornos de desarrollo</tipo>
                <descripcion>Que es un IDE (Entorno de Desarrollo Integrado) y como usarlo</descripcion>
            </UD>
            <UD numero="3">
                <tipo>Optimizacion y documentacion</tipo>
                <descripcion>Refactorización de código, uso de GitHub, repositorios y su documentación</descripcion>
            </UD>
        </contenidos>
    </modulo>

</moduloCFGS>
