=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad5/CFGS.dtd
<!ELEMENT cfgs (alumno*)>
<!ELEMENT alumno (nif, resultado, observaciones, IP, MAC)>
<!ELEMENT nif (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>
<!ATTLIST resultado opcion CDATA #FIXED "apto/no apto">
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT IP (#PCDATA)>
<!ELEMENT MAC (#PCDATA)>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad5/CFGS_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cfgs SYSTEM "CFGS.dtd">

<cfgs>
    <alumno>
        <nif>22233344A</nif>
        <resultado opcion="apto/no apto">Apto</resultado>
        <observaciones>El alumno tiene disponibilidad geogr√°fica.</observaciones>
        <IP>192.158.1.38</IP>
        <MAC/>
    </alumno>

    <alumno>
        <nif>45678912B</nif>
        <resultado opcion="apto/no apto">No apto</resultado>
        <observaciones/>
        <IP/>
        <MAC>8C:1B:A5:11:14:93</MAC>
    </alumno>
</cfgs>
