=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad1/Libreria.dtd
<!ELEMENT libreria (manga*)>
<!ELEMENT manga (autores, titulo, editorial, isbn, fecha-publicacion, genero, tomos)>
<!ELEMENT autores (autor*)>
<!ELEMENT autor (nombre, apellidos, sexo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT fecha-publicacion (dia, mes, año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT tomos (#PCDATA)>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad1/Libreria.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE libreria SYSTEM "Libreria.dtd">
<libreria xmlns:a="https://www.listadomanga.es/lista.php">

    <a:manga>
        <a:autores>
            <a:autor sexo="Mujer">
                <a:nombre>Tsukumizu</a:nombre>
                <a:apellidos/>
            </a:autor>
        </a:autores>
        <a:titulo>Girls' last tour</a:titulo>
        <a:editorial>Planeta Comic</a:editorial>
        <a:isbn>ISBN: 978-84-1341-203-0</a:isbn>
        <a:fecha-publicacion>
            <a:dia>15</a:dia>
            <a:mes>09</a:mes>
            <a:año>2021</a:año>
        </a:fecha-publicacion>
        <a:genero>Seinen</a:genero>
        <a:tomos>6</a:tomos>
    </a:manga>

    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Hiroaki</a:nombre>
                <a:apellidos>Samura</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>La espada del inmortal</a:titulo>
        <a:editorial>Ediciones Glénat</a:editorial>
        <a:isbn>ISBN: 978-84-7904-393-3</a:isbn>
        <a:fecha-publicacion>
            <a:dia>25</a:dia>
            <a:mes>05</a:mes>
            <a:año>1997</a:año>
        </a:fecha-publicacion>
        <a:genero>Seinen</a:genero>
        <a:tomos>30</a:tomos>
    </a:manga>

    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Ryo</a:nombre>
                <a:apellidos>Mizuno</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Lodoss War La Bruja Gris (Edición Integral)</a:titulo>
        <a:editorial>Planeta Comic</a:editorial>
        <a:isbn>ISBN: 978-84-684-7567-7</a:isbn>
        <a:fecha-publicacion>
            <a:dia>22</a:dia>
            <a:mes>09</a:mes>
            <a:año>2011</a:año>
        </a:fecha-publicacion>
        <a:genero>Shonen</a:genero>
        <a:tomos>1</a:tomos>
    </a:manga>
    
    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Junji</a:nombre>
                <a:apellidos>Ito</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Uzumaki</a:titulo>
        <a:editorial>Planeta de Agostini</a:editorial>
        <a:isbn>ISBN: 978-84-914-6584-3</a:isbn>
        <a:fecha-publicacion>
            <a:dia>17</a:dia>
            <a:mes>10</a:mes>
            <a:año>2017</a:año>
        </a:fecha-publicacion>
        <a:genero>Seinen</a:genero>
        <a:tomos>1</a:tomos>
    </a:manga>
        
    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Takehiko</a:nombre>
                <a:apellidos>Inoue</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Vagabond</a:titulo>
        <a:editorial>IVREA</a:editorial>
        <a:isbn>ISBN: 978-84-159-2294-0</a:isbn>
        <a:fecha-publicacion>
            <a:dia>17</a:dia>
            <a:mes>09</a:mes>
            <a:año>1998</a:año>
        </a:fecha-publicacion>
        <a:genero>Seinen</a:genero>
        <a:tomos>37</a:tomos>
    </a:manga>
        
    <a:manga>
        <a:autores>
            <a:autor sexo="Mujer">
                <a:nombre>Rumiko</a:nombre>
                <a:apellidos>Takahashi</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Lamu, Urusei Yatsura</a:titulo>
        <a:editorial>Glénat</a:editorial>
        <a:isbn>ISBN: 978-09-292-7964-0</a:isbn>
        <a:fecha-publicacion>
            <a:dia>01</a:dia>
            <a:mes>01</a:mes>
            <a:año>1990</a:año>
        </a:fecha-publicacion>
        <a:genero>Shonen</a:genero>
        <a:tomos>15</a:tomos>
    </a:manga>
        
    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Kiyohiko</a:nombre>
                <a:apellidos>Azuma</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>¡Yotsuba!</a:titulo>
        <a:editorial>Norma Editorial</a:editorial>
        <a:isbn>ISBN: 978-84-9814-360-7</a:isbn>
        <a:fecha-publicacion>
            <a:dia>28</a:dia>
            <a:mes>09</a:mes>
            <a:año>2005</a:año>
        </a:fecha-publicacion>
        <a:genero>Shonen</a:genero>
        <a:tomos>15</a:tomos>
    </a:manga>
        
    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Akira</a:nombre>
                <a:apellidos>Toriyama</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Dr. Slump</a:titulo>
        <a:editorial>Planeta DeAgostini</a:editorial>
        <a:isbn>ISBN: 978-84-917-3782-7</a:isbn>
        <a:fecha-publicacion>
            <a:dia>04</a:dia>
            <a:mes>11</a:mes>
            <a:año>2009</a:año>
        </a:fecha-publicacion>
        <a:genero>Shonen</a:genero>
        <a:tomos>15</a:tomos>
    </a:manga>
        
    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Katsuhiro</a:nombre>
                <a:apellidos>Otomo</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Akira</a:titulo>
        <a:editorial>Norma Editorial</a:editorial>
        <a:isbn>ISBN: 978-84-679-3256-0</a:isbn>
        <a:fecha-publicacion>
            <a:dia>20</a:dia>
            <a:mes>12</a:mes>
            <a:año>1982</a:año>
        </a:fecha-publicacion>
        <a:genero>Seinen</a:genero>
        <a:tomos>6</a:tomos>
    </a:manga>

    <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Yoshiyuki</a:nombre>
                <a:apellidos>Sadamoto</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Neon Genesis Evangelion</a:titulo>
        <a:editorial>Norma Editorial</a:editorial>
        <a:isbn>ISBN: 978-84-8431-743-2</a:isbn>
        <a:fecha-publicacion>
            <a:dia>26</a:dia>
            <a:mes>12</a:mes>
            <a:año>1994</a:año>
        </a:fecha-publicacion>
        <a:genero>Shonen</a:genero>
        <a:tomos>14</a:tomos>
    </a:manga>

        <a:manga>
        <a:autores>
            <a:autor sexo="Hombre">
                <a:nombre>Kazuhiko</a:nombre>
                <a:apellidos>Katou</a:apellidos>
            </a:autor>
        </a:autores>
        <a:titulo>Lupin III</a:titulo>
        <a:editorial>Panini Comics</a:editorial>
        <a:isbn>ISBN: 978-84-9167-589-1</a:isbn>
        <a:fecha-publicacion>
            <a:dia>30</a:dia>
            <a:mes>08</a:mes>
            <a:año>2018</a:año>
        </a:fecha-publicacion>
        <a:genero>Seinen</a:genero>
        <a:tomos>7</a:tomos>
    </a:manga>
    
</libreria>
