=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad2-3/Concesionario.dtd
<!ELEMENT concesionario (coche*)>
<!ELEMENT coche (codigo-de-coche, marca, modelo, matricula, potencia, plazas, numero-puertas)>
<!ELEMENT codigo-de-coche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numero-puertas (#PCDATA)>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad2-3/Concesionario.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE libreria SYSTEM "Concesionario.dtd">

<concesionario>
    <coche>
        <codigo-de-coche>LJCPCBLCX11000237</codigo-de-coche>
        <marca>Toyota</marca>
        <modelo>GT86</modelo>
        <matricula>1234ABC</matricula>
        <potencia>200</potencia>
        <plazas>4</plazas>
        <numero-puertas>2</numero-puertas>
    </coche>
</concesionario>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad2-3/EsquemaConcesionario.xml
<!DOCTYPE Concesionario SYSTEM "Concesionario.dtd">

<concesionario>
    <coche>
        <codigo-de-coche></codigo-de-coche>
        <marca></marca>
        <modelo></modelo>
        <matricula></matricula>
        <potencia></potencia>
        <plazas></plazas>
        <numero-puertas></numero-puertas>
    </coche>
</concesionario>
