=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad4/Clientes.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">

<xs:element name="sede">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="alta" maxOccurs="unbounded">
                <xs:complextype>
                    <xs:sequence>
                        <xs:element name="empleado-alta" maxOccurs="unbounded"/>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="codigo-sede" type="xs:string"/>
                                    <xs:element name="empleado" type="xs:string"/>
                                    <xs:element name="fecha" type="xs:string"/>
                                    <xs:element name="descripcion-cliente" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        <xs:element name="cliente" maxOccurs="unbounded"/>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="codigo-cliente" type="xs:string"/>
                                    <xs:element name="numero" type="xs:string"/>
                                    <xs:element name="coste" type="xs:string"/>
                                    <xs:element name="resumen" type="xs:string"/>
                                    <xs:element name="plazo" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad4/Clientes_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
 
<sede xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clientes.xsd">
    <alta>
        <empleado-alta >
            <codigo-sede>A1234567</codigo-sede>
            <empleado>Roberto Martinez Dembow</empleado>
            <fecha>13/01/2023</fecha>
            <descripcion-cliente>Solvente</descripcion-cliente>
        </empleado-alta>

        <clienteNDatos >
            <codigo-cliente formato="XYZ-1-2-3">ABC-7-4-1</codigo-cliente>
            <numero>1</numero>
            <coste>250000</coste>
            <resumen>Casa simple</resumen>
            <plazos>6</plazos>
        </clienteNDatos>
    </alta>
</sede>
