=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad4/Clientes.dtd
<!ELEMENT clientes (sede*)>
<!ELEMENT sede (direccion, nombreempleado, fecha, descripcion, cliente*)>
<!ELEMENT cliente (numero, coste, resumen, plazos)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombreempleado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazos (#PCDATA)>

=== Jcorvil/JorgeCoronil-UD4_LMSGT/Actividad4/Clientes_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE sede SYSTEM "Clientes.dtd">

<clientes>
    <sede codigo="A1234567">
        <direccion>Avda. Parlamentarios 8</direccion>
        <nombreempleado>Roberto Martinez</nombreempleado>
        <fecha>2023/01/23</fecha>
        <descripcion>Solvente</descripcion>
        <cliente codigo="ABC-1-2-3">
            <numero>1</numero>
            <coste>150000</coste>
            <resumen>Casa simple</resumen>
            <plazos>5</plazos>
        </cliente>
    </sede>
</clientes>
